# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchList', '0003_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='show_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchList.Show'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('user', 'show_id')]),
        ),
    ]
