# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchList', '0005_auto_20161123_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='show_details',
        ),
    ]
