# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchList', '0006_auto_20161123_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set([('user', 'show_id')]),
        ),
    ]
