# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 08:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchList', '0008_remove_watchlist_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'episode': 1, 'season': 1}),
        ),
    ]
