branch-defaults:
  master:
    environment: starter-dev
    group_suffix: null
global:
  application_name: starter
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: git
